Feature
nganifaith/restaurant_page pull request #1
Opened 2021-05-30 20:04 UTC by nganifaith

2021-05-30 23:19 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi Ngani, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-05-30 23:19 UTC, arslanbisharat commented on README.md
> +[Live site](https://nganifaith.github.io/library-app/)
- [ ] The link you have added is for the library app. Please update it with the restaurant app.

2021-05-30 23:19 UTC, arslanbisharat commented on README.md
> +Feel free to check the [issues page](https://github.com/nganifaith/library-app/issues).
- [ ] The issue page link you have added here takes the user to the library app issue page. Please update with the proper link.

2021-05-30 23:19 UTC, arslanbisharat commented on src/contact.js
> +export default function contactPage() {
- [ ] It would be great if you use ES6 syntax here. For example, don't export a function before defining a function and use arrow functions.

2021-05-30 23:19 UTC, arslanbisharat commented on src/header.js
> +export const renderSection = (section) => {
- [ ] It would be great if you use ES6 syntax here. For example, don't export a function before defining a function.

2021-05-30 23:19 UTC, arslanbisharat commented on src/header.js
> +export function headers() {
- [ ] It would be great if you use ES6 syntax here. For example, don't export a function before defining a function and use arrow functions.

2021-05-30 23:19 UTC, arslanbisharat commented on src/home.js
> +export default function homePage() {
- [ ] It would be great if you use ES6 syntax here. For example, don't export a function before defining a function and use arrow functions.

2021-05-30 23:19 UTC, arslanbisharat commented on src/menu.js
> +export default function menuPage() {
- [ ] It would be great if you use ES6 syntax here. For example, don't export a function before defining a function and use arrow functions.

2021-05-30 23:19 UTC, arslanbisharat commented on src/style.css
> +#content {
- [ ] Please avoid using ids as selectors in CSS. This is not a good practice to use IDs. Instead, you should use classes.

2021-05-30 23:19 UTC, arslanbisharat commented on README.md
> +![screenshot](./assets/menu.png)
- [ ] [Optional] It would be great if you add more screenshots in the Readme.

2021-05-31 13:41 UTC, UmairArshadDev approved these changes
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @nganifaith ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
HAPPY CODING :computer:
**Umair**

2021-05-31 13:58 UTC, merged